[tox]
skipsdist = True

[testenv:integration]
deps =
    pytest
    pytest-operator
    pytest-asyncio
    juju
commands =
    pytest {posargs} tests/integration/ -v
passenv =
    HOME
    JUJU_*
    KUBECONFIG

[pytest]
asyncio_mode = auto
