"""Core logic for ``opcli pytest expand``.

Reads ``artifacts-generated.yaml`` (schema v1) and assembles the flags that
tox/pytest need to locate built charms and their OCI-image resources.

Convention (matching operator-workflows):
    --charm-file=<path>             for each locally built charm
    --<rock-name>-image=<path>      for each rock (directly, regardless of charm links)
    --<resource-name>=<path>        for OCI-image resources not backed by a rock

Rock image flags are generated by iterating over ``rocks`` directly, so no
explicit ``rock:`` annotation in ``artifacts.yaml`` is required.  The
``rock:`` field is still used for publishing (knowing which rock backs which
charm resource), but it is not needed for test flag generation.

The ``KEY=VALUE`` form is required because some conftest.py files register
``--charm-file`` with ``nargs="+"``, which makes argparse greedy.  With the
space-separated form, subsequent ``--charm-file`` tokens would be consumed as
values of the first flag instead of starting a new flag.

When the generated file contains multi-arch builds, flags are filtered to the
current machine's architecture.  If no build matches the current arch, all
available builds are used (graceful degradation for single-arch repos).
"""

from __future__ import annotations

import logging
import platform
from pathlib import Path
from typing import overload

from opcli.core.exceptions import ConfigurationError
from opcli.core.yaml_io import load_artifacts_generated
from opcli.models.artifacts_generated import (
    CharmArchBuild,
    RockArchBuild,
    SnapArchBuild,
)

logger = logging.getLogger(__name__)

_ARTIFACTS_GENERATED_YAML = "artifacts-generated.yaml"


def _current_arch() -> str:
    """Return the normalised architecture of the current machine."""
    machine = platform.machine().lower()
    if machine in ("x86_64", "amd64"):
        return "amd64"
    if machine in ("aarch64", "arm64"):
        return "arm64"
    return machine


@overload
def _select_arch_builds(
    builds: list[RockArchBuild], arch: str, artifact_name: str
) -> list[RockArchBuild]: ...


@overload
def _select_arch_builds(
    builds: list[CharmArchBuild], arch: str, artifact_name: str
) -> list[CharmArchBuild]: ...


@overload
def _select_arch_builds(
    builds: list[SnapArchBuild], arch: str, artifact_name: str
) -> list[SnapArchBuild]: ...


def _select_arch_builds(
    builds: list[RockArchBuild] | list[CharmArchBuild] | list[SnapArchBuild],
    arch: str,
    artifact_name: str,
) -> list[RockArchBuild] | list[CharmArchBuild] | list[SnapArchBuild]:
    """Return the subset of *builds* matching *arch*, or all if none match.

    When an exact arch match is found, only those builds are returned.
    When no build matches the current arch (e.g. running arm64 tests against
    an amd64-only artifact set), all builds are returned with a warning so
    that single-arch repos continue to work.
    """
    matching = [b for b in builds if b.arch == arch]
    if matching:
        return matching  # type: ignore[return-value]
    if builds:
        logger.warning(
            "No build for '%s' matches arch '%s'; using all available builds: %s",
            artifact_name,
            arch,
            [b.arch for b in builds],
        )
    return builds


def assemble_pytest_args(
    root: Path,
) -> list[str]:
    """Build the list of pytest flags from the generated artifacts.

    Returns:
        A list of CLI flags like
        ``["--charm-file=path.charm", "--img=path.rock"]``.

    Raises:
        ConfigurationError: If ``artifacts-generated.yaml`` is missing.
    """
    gen_path = root / _ARTIFACTS_GENERATED_YAML
    if not gen_path.exists():
        msg = (
            f"{_ARTIFACTS_GENERATED_YAML} not found. Run 'opcli artifacts build' first."
        )
        raise ConfigurationError(msg)

    generated = load_artifacts_generated(gen_path)
    arch = _current_arch()

    args: list[str] = []

    # Rock image flags — one per rock, matching operator-workflows convention.
    # This runs unconditionally so no rock: annotation is needed on charm resources.
    rock_flag_names: set[str] = set()
    for rock in generated.rocks:
        rock_builds = _select_arch_builds(rock.output, arch, rock.name)
        for rock_build in rock_builds:
            value = rock_build.image or rock_build.file
            if value:
                flag_name = f"{rock.name}-image"
                rock_flag_names.add(flag_name)
                args.append(f"--{flag_name}={value}")

    for charm in generated.charms:
        charm_builds = _select_arch_builds(charm.output, arch, charm.name)
        for charm_build in charm_builds:
            if charm_build.files:
                for charm_file in charm_build.files:
                    args.append(f"--charm-file={charm_file.path}")
            elif charm_build.artifact:
                logger.warning(
                    "Skipping --charm-file for charm '%s' (%s): output is a CI "
                    "artifact (%s). Run 'opcli artifacts build' locally to get "
                    "a local file.",
                    charm.name,
                    charm_build.arch,
                    charm_build.artifact,
                )

        # Resources backed by a rock are already covered by the rock
        # iteration above. Resources without a rock link have no output info.
        for res_name, res in (charm.resources or {}).items():
            if res.rock:
                continue
            if res_name in rock_flag_names:
                logger.warning(
                    "Skipping resource '%s' for charm '%s': flag name '--%s' "
                    "already emitted by a rock with the same name.",
                    res_name,
                    charm.name,
                    res_name,
                )
                continue

    return args


def assemble_tox_argv(
    root: Path,
    *,
    tox_env: str = "integration",
    extra_args: list[str] | None = None,
) -> list[str]:
    """Build the full tox argv for running integration tests.

    Returns a list of tokens suitable for shell execution or display via
    ``shlex.join()``.  The ``--`` separator is included only when there are
    pytest flags or forwarded extra args to pass.

    Raises:
        ConfigurationError: If required YAML files are missing.
    """
    assembled = assemble_pytest_args(root)
    pytest_args = assembled + (extra_args or [])

    cmd: list[str] = ["tox", "-e", tox_env]
    if pytest_args:
        cmd += ["--", *pytest_args]
    return cmd
